### ISSUE TITLE
Is NOTICE correct?

### ISSUE THREAD

**Issue by dblock** [AmiStrn/Plugin-Template#2]
https://github.com/AmiStrn/Plugin-Template/blob/main/NOTICE.txt says code includes Joda, ElasticSearch, etc. Is this correct?

**Comment by AmiStrn** [comment]
It is a copy from opensearch if im not mistaken, ill fix it up. Just wanted to cut down all the extra stuff. 
Still missing a security props file for example.

**Comment by AmiStrn** [comment]
Fixed by [commit 39c7fa14db7989151a790f1a79cd953f3368c750](https://github.com/AmiStrn/Plugin-Template/commit/39c7fa14db7989151a790f1a79cd953f3368c750)
This was committed directly so I'm closing this issue without a pr related to it :/
